USE [master]
GO

/****** Object:  Database [PortoT]    Script Date: 11/03/2021 17:54:12 ******/
CREATE DATABASE [PortoT]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PortoT', FILENAME = N'E:\sql\MSSQL14.SQLEXPRESS\MSSQL\DATA\PortoT.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PortoT_log', FILENAME = N'E:\sql\MSSQL14.SQLEXPRESS\MSSQL\DATA\PortoT_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PortoT].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PortoT] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PortoT] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PortoT] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PortoT] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PortoT] SET ARITHABORT OFF 
GO

ALTER DATABASE [PortoT] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [PortoT] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PortoT] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PortoT] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PortoT] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PortoT] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PortoT] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PortoT] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PortoT] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PortoT] SET  DISABLE_BROKER 
GO

ALTER DATABASE [PortoT] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PortoT] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PortoT] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PortoT] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PortoT] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PortoT] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [PortoT] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PortoT] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [PortoT] SET  MULTI_USER 
GO

ALTER DATABASE [PortoT] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PortoT] SET DB_CHAINING OFF 
GO

ALTER DATABASE [PortoT] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [PortoT] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [PortoT] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [PortoT] SET QUERY_STORE = OFF
GO

ALTER DATABASE [PortoT] SET  READ_WRITE 
GO


