USE [PortoT]
GO

/****** Object:  View [dbo].[TOTAL_MOVIMENTACOES_CLIENTE]    Script Date: 11/03/2021 17:55:15 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[TOTAL_MOVIMENTACOES_CLIENTE]

AS

--TOTAL DE MOVIMENTAÇÕES POR CLIENTE
SELECT
C.ID_CLIENTE [Código Cliente]
,C.NOME_CLIENTE [Nome do Cliente]
,C.NUM_CONTAINER  [Número do Contêiner]
,C.TIPO_CONTAINER  [Tipo]
,C.STATUS_CONTAINER  [Status]
,C.CATEGORIA_CONTAINER [Categoria]
,M.TIPO_MOVIMENTACAO [Tipo de Movimentação]
,COUNT(M.TIPO_MOVIMENTACAO) AS [Movimentação Total]
FROM TBCONTAINER C  
INNER JOIN TBMOVIMENTACAO M  
ON C.ID_CLIENTE = M.ID_CLIENTE  
GROUP BY 
C.ID_CLIENTE
,C.NOME_CLIENTE
,C.NUM_CONTAINER  
,C.TIPO_CONTAINER  
,C.STATUS_CONTAINER  
,C.CATEGORIA_CONTAINER
,M.TIPO_MOVIMENTACAO  
GO


